# Generated by Django 3.1.5 on 2021-02-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orthanc_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orthanc',
            new_name='OrthancInstance',
        ),
    ]
