# Generated by Django 3.1.5 on 2021-02-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthanc_manager', '0002_auto_20210217_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthancinstance',
            name='has_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orthancinstance',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orthancinstance',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
