# Generated by Django 3.1.5 on 2021-02-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orthanc_manager', '0003_auto_20210217_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthancinstance',
            name='aet',
        ),
    ]
